[package]
name = "polish-calculator"
version = "0.1.0"
authors = ["Ricardo Domingos <ricardohsd@gmail.com>"]
edition = "2018"

[lib]
name = "rpn"
path = "src/lib.rs"

[[bin]]
name = "calculator"
path = "src/main.rs"

[dependencies]
